zodiac_inp = str(input("Please enter your zodiac sign. If you don't know please enter the following details:"))


Aries = "There's an extra spark in your eye that people won't be able to ignore. Today's a good day to get your point across, because you'll find people more open and receptive to new things than usual. Speak with confidence and you'll go far. It's important for you to say what you feel. If you don't, others will find reasons to walk all over you."
Taurus = "Take yourself on a mental adventure today in which you explore new aspects of your world. Discuss philosophy and religion. Get to the core of a matter that seriously interests you. Now is a good time to consider taking classes or engaging in some form of higher learning. Your emotions come from a point of great power and you should use this energy wisely."
Gemini = "Today is your day, Gemini, so live it up! If it seems like things have been rather intense lately, don't worry, they're apt to lighten up quite a bit today. Feel free to be your usual jolly self, the one who adds humor to the group. Your laughter will be appreciated. Come into the forefront. Bring things up to your level and you'll find that others willingly join you there."
Cancer = "Be careful that you aren't acting in a way that you dislike in others, Cancer. You could find that you're slowly taking on the traits of the people you despise. Lighten up a bit and put a smile on your face. If you continue to see the negative side of everything, it's likely that other people will only see the negative side of you."
Leo = "The day's general mood should fit quite well with your agenda, Leo. There's no need to fixate on the negative. Keep things light and upbeat and worry about the consequences later. This is the time to be adventurous and explore. Don't let anyone else tell you how to run your show. You have a strong will and strong opinions, so don't be afraid to express either."
Virgo = "You may need a translator to get through to people today, Virgo. It could be hard to make decisions, but not impossible. Today's tip is to err on the side of adventure. Trust that good luck will pull you through if you take risks. You may feel unappreciated. Ask for help when you need it, but don't rely on others to heal you. Most of this work needs to come from within."
Libra = "Use your power resources today, Libra, as you have a great deal of dynamic energy at your disposal. You have the ability to transform and conquer anything now. Note that your spirit of adventure is apt to be more acute than normal, and you may be feeling quite anxious to get things rolling in a new direction. Don't hold back. Now is the time to do things full force."
Scorpio = "You could be asked to make some spontaneous decisions today that you might not feel entirely comfortable making, Scorpio. You could feel you don't have enough facts to make an educated decision about what to do next. Realize that sometimes it's necessary to bite the bullet and make the best choice based on the knowledge you have. Be adventurous and trust your judgment."
Sagittarius = "Emotionally, you may feel as if you're running up against a brick wall, Sagittarius. It could be that your first reaction is to drown your sorrows in drink. Escapism is only a temporary remedy. If things slam in your face today, use this as an indication that you need to take necessary action. Don't keep bouncing around from one thing to the next in order to avoid the obvious. Face the music."
Capricorn = "Your emotions could be extra powerful today, Capricorn, although something may not feel as if it's sitting right. It could be a feeling of manipulation. Perhaps you've misjudged someone else's sensitivity and now they're working to get back at you in a subtle yet harmful way. Attend to your feelings and spend time alone if it helps you get more in tune with your emotions."
Aquarius = "Take hold of this day as if it's your own and use it to grow your dreams, Aquarius. You'll find a great deal of power and dynamism in the air urging you to take the adventurous route. There's no need to hold back. The door is open and waiting for you to take the leap of faith to the other side. Don't even worry about consequences now. Your good luck will pull you safely through."
Pisces = "There's a fiery tone to the day that can't be ignored, Pisces. You may find that adjustments need to be made in your own plan of attack in order to get on the same page with other people. Don't worry if things don't go according to your plans. In fact, the best route to take is the one that wasn't even planned. Do something that you've never done before."

horoscope = {"Aries": Aries, "Taurus": Taurus, "Gemini": Gemini, "Cancer": Cancer, "Leo": Leo, "Virgo": Virgo, "Libra": Libra, "Scorpio": Scorpio, "Sagittarius": Sagittarius, "Capricorn": Capricorn, "Aquarius": Aquarius, "Pisces": Pisces}

for i in horoscope:
    if i == zodiac_inp:
        print("Your horoscope says that: ", horoscope.get(i))
