from random import  random
def function2():
        horoscope={
            'Aries':'Clean and green is your motto for the next month, thanks to the Sun’s tour of your sixth house of health and organization. You’ve got the motivation to make your world run smoothly, and to get your wellness goals on track. If you’ve had one too many margaritas or let your paperwork fall behind this summer, don’t waste time berating yourself. Perfectionism isn’t attainable, Aries, so how about settling for streamlined systems and a sustainable fitness routine? A trip to Lowe’s may be in order, and perhaps also your favorite sports outlet for a new pair of cross-trainers. Set yourself up for success, and sign up for an activity you actually enjoy.',
            'Taurus':'Ready, set, play! The Sun slides into your joyful and creative fifth house for the next month. You might have curled up in your cocoon or felt down in the dumps for the past 30 days. But now, you’re ready to shake off those vibes and have some fun. Feel free to share your talents and express your opinions when the spirit moves you. Should you be struck with the urge to make a radical style change, the cosmos give you clearance. Bring on the bold prints and a brand new do!',
            'Gemini': 'Your nesting instincts kick in hardcore today as Sun slides into your domestic fourth house. The next month is about nurturing Numero Uno in the name of being emotionally grounded. Besides amping up self-care, add some fresh aesthetic touches to Casa Twin, or cozy up with your closest family members. Spending some time in the kitchen is also good for your soul, so why not try out some seasonal autumn recipes. Looking to hang your hat elsewhere? El sol makes your search that much easier. Family members and inner circle friends assume starring roles over the next 30 days. ',
            'Cancer': 'The social scene is calling your name! Today, the Sun enters Virgo and your garrulous third house for the next month, helping you wrap up summer in mixing-and-mingling mode. Expect your calendar to fill up with intriguing characters, lively get-togethers, and overall good times between now and September 22. Also, your mind couldn’t be any sharper now, so be sure to record your flashes of insight and original ideas. Perhaps even pen a blog or the beginnings of a book. The local scene also proves to be fulfilling. Register for a workshop, or jump in on a community project. ',
            'Leo': 'Next stop: Prosperity Central. The Sun moves into industrious Virgo and your second house of work and money. This month-long cycle is all about concretizing the musings and desires you connected to while the Sun was in your sign over the last 30 days. This solar energy infuses you with motivation mojo, and kicks you into manifesting mode. Use this phase to tackle the most pressing items. Prioritize the tasks at hand, and reconfigure your routines to maximize success. Keep it simple, and you’ll maintain minimal stress levels. Draft out an action plan over the weekend, and get pumped about putting into practice.',
            'Virgo': 'Happy birthday to you! The Sun blazes into Virgo, rousing you from a sleepy month. Your energy levels start building momentum now, motivating you to start your solar return on a positive and productive note. Take time to compose a list of your goals, and perhaps post it somewhere visible to keep you on track. Dive headfirst into a passion project, or advance a personal goal. Putting yourself out in the public eye bodes well between now and September 22, so if you’ve been pondering taking that leap, now’s the time to do it. Numero Uno deserves to sit at the top of the list. Enjoy!',
            'Libra': 'Shift into the slow lane, Libra. Today, the Sun moves into Virgo and your twelfth house of respite and completions. The next 30 days are about tying up loose ends and putting pending issues to rest. Your mojo levels could be lagging, so listen to your body and squeeze in siestas when you can. Also, conserve your energy by enforcing limits with those “me, me, me” people in your life. Taking care of Numero Uno is more important right now. Scale back your social schedule, too. You hate to miss a party, but if you try to do it all you’re only asking for exhaustion. ',
            'Scorpio':'Time to expand your roster of friends in high places, as the Sun moves into Virgo and your eleventh house of networking for the next four weeks. Your social schedule will soon be bursting at the seams, giving you a wide array of intriguing people in which to join forces. Even though you’ll be busy swapping ideas, there’ll still be plenty of fun to go around. You’ve been working like a fiend over the last month, and so take this planetary pass to let your hair down.',
            'Sagittarius':'Success is knocking at your door, Sagittarius. Starting today, the Sun begins a four-week tour of Virgo and your ambitious tenth house. Take a few days to review and revamp your grand career goals. Draft out an action plan and timeline for the rest of the year. What rung of the ladder would like to be perched up on before your birthday rolls around? Your vision is solid and strategic skills are especially sharp, so put ‘em to good use. ',
            'Capricorn': 'Expand your horizons! Today, the Sun blasts into your ninth house of travel and education for the next month, giving you the urge to open new doors. Let curiosity be your guide. Between now and September 22, head out on an adventurous weekend road trip, sign up for an intriguing workshop, set plans in motion for that study-abroad trip you’ve always fantasized about. Seize any and all chances to sate your love of learning. A wide world of opportunity awaits. Carpe diem! ',
            'Aquarius': 'Small talk won’t cut it starting today as the Sun slides into your soulful and private eighth house for the next month. You’ll prefer intense conversations with a select few rather than scattering your energy over many social obligations. It’s all about quality over quantity now, Aquarius. This cycle is also a stellar time for researching and soul-searching. When it comes to a certain relationship, officializing vibes are in the air. Between now and September 22, you may be putting a ring on it, moving in together, or conversely, breaking free from a restrictive bond. On the business front, a partnership could form, so seek out people who have the skills and resources you lack, and vice versa.',
            'Pisces': 'The best things come in pairs, Pisces! Today, the Sun settles into Virgo and your seventh house of partnerships for the next month. Unexpected “clicks” and opportunities to collaborate could land in your lap, but also be proactive. Be it for business or pleasure, keep your radar honed for potential people to join forces with. If you’ve put that special someone on the back burner lately, carve out quality time together. Nurture your important relationships—especially with those people who’ve always had your back.'
        }
        print(random.choice(list(horoscope.items())))
if __name__=='__main__':
    function2()
